name: eb-pipeline

on:
  push:
    branches: [dev, main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set env vars (dev)
        if: endsWith(github.ref, '/dev')
        run: |
          echo "EB_ENV=chris-flask-app-dev" >> $GITHUB_ENV

      - name: Set env vars (prod)
        if: endsWith(github.ref, '/prod')
        run: |
          echo "EB_ENV=chris-flask-app-prod" >> $GITHUB_ENV

      - uses: actions/checkout@v2

      - name: Create ZIP deployment package
        run: zip -r deploy_package.zip ./

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Upload package to S3 bucket
        run: aws s3 cp deploy_package.zip s3://dev-chris-all-purposes/

      - name: Create new ElasticBeanstalk application version
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name chris-flask-app \
          --source-bundle S3Bucket="dev-chris-all-purposes",S3Key="deploy_package.zip" \
          --version-label "ver-${{ github.sha }}" \
          --description "commit-sha-${{ github.sha }}"

      - name: Update prod environment with new application version]
        run: |
          aws elasticbeanstalk update-environment \
          --environment-name ${{ env.EB_ENV }} \
          --version-label "ver-${{ github.sha }}"
